export const products = [
  {
    id: "1",
    sku: "NL-001",
    title: "Cutting Nozzle A 1.0mm",
    slug: "cutting-nozzle-a-1-0mm",
    brand: "Raytools",
    head: "BT240",
    category: "cutting-nozzle",
    price: 120,
    mrp: 180,
    stock: 40,
    images: ["https://res.cloudinary.com/demo/image/upload/nozzle1.jpg"],
    short: "High precision Raytools nozzle for BT240 head.",
    description:
      "<p>High-quality laser cutting nozzle designed for BT240 heads. Ensures stable focal length and clean cut.</p>",
    specs: { diameter: "1.0mm", material: "Copper" },
    meta: {
      title: "Cutting Nozzle A 1.0mm - Raytools",
      description:
        "Raytools BT240 nozzle for clean and accurate laser cutting.",
      keywords: "cutting nozzle, raytools nozzle, bt240",
    },
  },
  {
    id: "2",
    sku: "NL-002",
    title: "Cutting Nozzle A 1.5mm",
    slug: "cutting-nozzle",
    brand: "Raytools",
    head: "BT240",
    category: "cutting-nozzles",
    price: 130,
    mrp: 190,
    stock: 50,
    images: ["https://res.cloudinary.com/demo/image/upload/nozzle2.jpg"],
    short: "Raytools 1.5mm nozzle for stable nitrogen/oxygen cutting.",
    description:
      "<p>Precision-machined nozzle suitable for mild steel, stainless steel, and aluminum cutting applications.</p>",
    specs: { diameter: "1.5mm", material: "Copper" },
    meta: {
      title: "Cutting Nozzle 1.5mm - Raytools",
      description: "High-performance 1.5mm Raytools nozzle for BT240.",
      keywords: "raytools nozzle, 1.5mm nozzle",
    },
  },
  {
    id: "3",
    sku: "NL-003",
    title: "Ceramic Ring for Raytools BT240",
    slug: "ceramic-ring",
    brand: "Raytools",
    head: "BT240",
    category: "ceramic-rings",
    price: 450,
    mrp: 600,
    stock: 20,
    images: ["https://res.cloudinary.com/demo/image/upload/ceramic1.jpg"],
    short: "High durability ceramic ring for Raytools BT240.",
    description:
      "<p>Premium ceramic ring with heat-resistant material for consistent laser performance.</p>",
    specs: { material: "Ceramic", compatibility: "BT240" },
    meta: {
      title: "Ceramic Ring BT240 - Raytools",
      description: "Long-lasting ceramic ring for Raytools BT240 heads.",
      keywords: "ceramic ring, raytools, bt240",
    },
  },
  {
    id: "4",
    sku: "NL-004",
    title: "Protective Lens 24.5×2mm",
    slug: "protective-lens",
    brand: "WSX",
    head: "WSX-NC30",
    category: "protective-lens",
    price: 350,
    mrp: 500,
    stock: 60,
    images: ["https://res.cloudinary.com/demo/image/upload/protective1.jpg"],
    short: "Anti-reflective coated protective lens for WSX heads.",
    description:
      "<p>Protective lens with AR coating ensuring extended head life and stable cutting protection.</p>",
    specs: { size: "24.5x2mm", coating: "AR" },
    meta: {
      title: "Protective Lens 24.5×2mm - WSX",
      description: "High-quality protective lens for WSX laser heads.",
      keywords: "protective lens, wsx lens",
    },
  },
  {
    id: "5",
    sku: "NL-005",
    title: "Protective Lens 27.9×4mm",
    slug: "protective-lens",
    brand: "Raytools",
    head: "BT210",
    category: "protective-lens",
    price: 420,
    mrp: 550,
    stock: 30,
    images: ["https://res.cloudinary.com/demo/image/upload/protective2.jpg"],
    short: "Thick protective lens ideal for high-power cutting.",
    description:
      "<p>Designed for heavy-duty cutting operations at 6kW and 12kW configurations.</p>",
    specs: { size: "27.9x4mm", coating: "AR+" },
    meta: {
      title: "Protective Lens 27.9×4mm - Raytools",
      description: "Premium thick lens for Raytools BT210.",
      keywords: "protective lens, raytools bt210",
    },
  },
  {
    id: "6",
    sku: "NL-006",
    title: "Focus Lens 20×4mm",
    slug: "focus-lens",
    brand: "Raytools",
    head: "BT240",
    category: "focus-lens",
    price: 1800,
    mrp: 2200,
    stock: 12,
    images: ["https://res.cloudinary.com/demo/image/upload/focus1.jpg"],
    short: "High precision focus lens for Raytools BT240.",
    description:
      "<p>Delivers tight beam quality for accurate cutting performance.</p>",
    specs: { size: "20x4mm", focal_length: "100mm" },
    meta: {
      title: "Focus Lens 20×4mm - Raytools",
      description: "Premium focus lens for accurate and clean laser cutting.",
      keywords: "focus lens, laser focus",
    },
  },
  {
    id: "7",
    sku: "NL-007",
    title: "Collimation Lens 18×5mm",
    slug: "collimation-lens",
    brand: "Raytools",
    head: "BT240",
    category: "rf-cable",
    price: 1600,
    mrp: 2000,
    stock: 10,
    images: ["https://res.cloudinary.com/demo/image/upload/collimation1.jpg"],
    short: "Collimation lens for stable beam shaping.",
    description:
      "<p>Ensures optimal collimation for consistent beam diameter during cutting.</p>",
    specs: { size: "18x5mm" },
    meta: {
      title: "Collimation Lens 18×5mm - Raytools",
      description: "High-quality collimation lens for precise laser cutting.",
      keywords: "collimation lens",
    },
  },

  {
    id: "8",
    sku: "NL-008",
    title: "Nozzle Single Layer 1.0mm – Precitec",
    slug: "nozzle",
    brand: "Precitec",
    head: "LightCutter",
    category: "rf-cable",
    price: 150,
    mrp: 200,
    stock: 70,
    images: ["https://res.cloudinary.com/demo/image/upload/nozzle3.jpg"],
    short: "Single layer cutting nozzle for Precitec LightCutter.",
    description:
      "<p>Designed for fast airflow and minimal spatter in stainless steel cutting.</p>",
    specs: { material: "H59 Brass", diameter: "1.0mm" },
    meta: {
      title: "Precitec Single Layer Nozzle 1.0mm",
      description: "High-speed cutting nozzle for Precitec laser heads.",
      keywords: "precitec nozzle",
    },
  },
  {
    id: "9",
    sku: "NL-009",
    title: "Ceramic Ring for WSX NC30",
    slug: "protective-lens",
    brand: "WSX",
    head: "NC30",
    category: "ceramic-rings",
    price: 480,
    mrp: 650,
    stock: 25,
    images: ["https://res.cloudinary.com/demo/image/upload/ceramic2.jpg"],
    short: "Heat-resistant WSX ceramic ring.",
    description:
      "<p>Durable ceramic ring with excellent thermal stability for NC30 heads.</p>",
    specs: { material: "Ceramic", compatibility: "NC30" },
    meta: {
      title: "WSX NC30 Ceramic Ring",
      description: "Long-lasting ceramic ring for WSX NC30 heads.",
      keywords: "wsx ceramic ring",
    },
  },
  {
    id: "10",
    sku: "NL-010",
    title: "Protective Lens 20×2mm",
    slug: "protective-lens-20x2mm",
    brand: "Raytools",
    head: "BT210",
    category: "protective-lens",
    price: 300,
    mrp: 450,
    stock: 55,
    images: ["https://res.cloudinary.com/demo/image/upload/protective3.jpg"],
    short: "Compact protective lens for mid-power laser heads.",
    description:
      "<p>High-temperature protective design suitable for 3kW and 4kW machines.</p>",
    specs: { size: "20x2mm", coating: "AR" },
    meta: {
      title: "Protective Lens 20×2mm",
      description: "Durable protective lens for medium power laser systems.",
      keywords: "protective lens raytools",
    },
  },
  {
    id: "11",
    sku: "NL-011",
    title: "Focus Lens 20×4mm – German Coated",
    slug: "focus-lens",
    brand: "HighGrade",
    head: "Universal",
    category: "focus-lens",
    price: 2200,
    mrp: 2600,
    stock: 15,
    images: ["https://res.cloudinary.com/demo/image/upload/focus2.jpg"],
    short: "German coated premium focus lens.",
    description:
      "<p>Improved focusing stability for fine detail cutting and minimal heat-affected zone.</p>",
    specs: { coating: "German AR+", focal_length: "125mm" },
    meta: {
      title: "German Coated Focus Lens 20×4mm",
      description: "Premium long-life focus lens for precision cutting.",
      keywords: "focus lens german coating",
    },
  },
  {
    id: "12",
    sku: "NL-012",
    title: "Nozzle Double Layer 1.0mm – Raytools",
    slug: "focus-lens",
    brand: "Raytools",
    head: "BT240",
    category: "cutting-nozzles",
    price: 180,
    mrp: 230,
    stock: 35,
    images: ["https://res.cloudinary.com/demo/image/upload/nozzle4.jpg"],
    short: "Double-layer nozzle for smoother airflow.",
    description:
      "<p>Reduces turbulence and spatter for high-quality cutting surface.</p>",
    specs: { type: "Double Layer", diameter: "1.0mm" },
    meta: {
      title: "Double Layer Raytools Nozzle",
      description: "Improved airflow and cutting performance.",
      keywords: "raytools double layer nozzle",
    },
  },
  {
    id: "13",
    sku: "NL-013",
    title: "WSX 1.2mm Cutting Nozzle",
    slug: "wsx-cutting-nozzle-1-2mm",
    brand: "WSX",
    head: "NC30",
    category: "cutting-nozzles",
    price: 140,
    mrp: 200,
    stock: 80,
    images: ["https://res.cloudinary.com/demo/image/upload/nozzle5.jpg"],
    short: "High-flow WSX nozzle for NC30.",
    description:
      "<p>Designed for fast nitrogen cutting with clean kerf lines.</p>",
    specs: { diameter: "1.2mm" },
    meta: {
      title: "WSX 1.2mm Cutting Nozzle",
      description: "High-speed nitrogen cutting nozzle for WSX NC30.",
      keywords: "wsx nozzle",
    },
  },
  {
    id: "14",
    sku: "NL-014",
    title: "Lens Holder — Raytools",
    slug: "lens-holder-raytools",
    brand: "Raytools",
    head: "BT240",
    category: "spare-parts",
    price: 950,
    mrp: 1200,
    stock: 10,
    images: ["https://res.cloudinary.com/demo/image/upload/holder1.jpg"],
    short: "Original Raytools lens holder for BT240.",
    description:
      "<p>Precision-machined holder for stable lens positioning.</p>",
    specs: { material: "Steel", compatibility: "BT240" },
    meta: {
      title: "Raytools Lens Holder",
      description: "Original Raytools BT240 lens holder.",
      keywords: "lens holder raytools",
    },
  },
  {
    id: "15",
    sku: "NL-015",
    title: "O-Ring Set (10pcs) for Laser Nozzles",
    slug: "o-ring-set-nozzles",
    brand: "Generic",
    head: "Universal",
    category: "o-rings",
    price: 120,
    mrp: 180,
    stock: 100,
    images: ["https://res.cloudinary.com/demo/image/upload/oring1.jpg"],
    short: "High-temperature O-rings for nozzle sealing.",
    description:
      "<p>Ensures leak-free gas flow and stable cutting performance.</p>",
    specs: { quantity: "10pcs" },
    meta: {
      title: "Laser Nozzle O-Ring Set",
      description: "Heat-resistant O-rings for universal nozzle heads.",
      keywords: "o-ring nozzle",
    },
  },
  {
    id: "16",
    sku: "NL-016",
    title: "Nozzle Single Layer 0.8mm – Precitec",
    slug: "nozzle-single-layer-0-8mm-precitec",
    brand: "Precitec",
    head: "LightCutter",
    category: "cutting-nozzles",
    price: 140,
    mrp: 180,
    stock: 50,
    images: ["https://res.cloudinary.com/demo/image/upload/nozzle6.jpg"],
    short: "Small-diameter nozzle for fine cutting.",
    description: "<p>Ideal for thin sheet metal and detail work.</p>",
    specs: { diameter: "0.8mm" },
    meta: {
      title: "Precitec 0.8mm Nozzle",
      description: "Precision nozzle for light cutting tasks.",
      keywords: "precitec small nozzle",
    },
  },
  {
    id: "17",
    sku: "NL-017",
    title: "Mirror Protective 30×5mm",
    slug: "mirror-protective-30x5mm",
    brand: "Generic",
    head: "CO2",
    category: "protective-lens",
    price: 600,
    mrp: 800,
    stock: 18,
    images: ["https://res.cloudinary.com/demo/image/upload/mirror1.jpg"],
    short: "Protective mirror for CO2 laser machines.",
    description:
      "<p>Durable mirror with gold coating for long operational life.</p>",
    specs: { size: "30x5mm" },
    meta: {
      title: "Protective Mirror 30×5mm",
      description: "High durability mirror for CO2 lasers.",
      keywords: "co2 mirror",
    },
  },
];
